# Generated by Django 5.0.7 on 2024-07-10 23:49

import compress_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepehr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('exercise_name', models.CharField(max_length=128, unique=True)),
                ('exercise_content', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('java_definition', compress_field.models.ZipFileField(upload_to='mycontent/')),
                ('cpp_definition', compress_field.models.ZipFileField(upload_to='mycontent/')),
            ],
        ),
    ]
