# Generated by Django 5.0.7 on 2024-07-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepehr', '0002_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
