# Generated by Django 5.0.7 on 2024-07-11 00:06

import compress_field.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepehr', '0003_exercise_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='cpp_definition',
            field=compress_field.models.ZipFileField(blank=True, upload_to='mycontent/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='java_definition',
            field=compress_field.models.ZipFileField(blank=True, upload_to='mycontent/'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sepehr.exercise')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sepehr.student')),
            ],
        ),
    ]
